variables:
  GRADLE_OPTS: "-Dorg:gradle.daemon=false"
  GIT_STRATEGY: clone
  GRADLE_VERSION: "7.5"
  RUNNER: "dalfcs_docker_kvm"#"dalfcs_docker_autoscale" # "grad" #"ugrad"  #
  JDK_VERSION: "jdk8"

before_script:
  - GRADLE_USER_HOME="$(pwd)/tripmate/.gradle"
  - export GRADLE_USER_HOME
  - cd tripmate

stages:
  - build
  - test
  - deploy

test:
  stage: test
  tags:
    - $RUNNER
  image: gradle:$GRADLE_VERSION-$JDK_VERSION # 7.5-jdk8
  script:
    - chmod +x ./gradlew
    - ./gradlew test
  artifacts:
    when: always
    paths:
      - tripmate/build/test-results/test
    reports:
      junit: tripmate/build/test-results/test/TEST-grp16.tripmate.TripmateApplicationTests.xml
  only:
    refs:
      - branches
# Ref: https://medium.com/trendyol-tech/reporting-test-results-in-gitlab-6c1938a7472e

build:
  stage: build
  tags:
    - $RUNNER
  image: gradle:$GRADLE_VERSION-$JDK_VERSION # 7.5-jdk8
  script:
    - chmod +x ./gradlew
    - ./gradlew assemble --scan
  only:
    refs:
      - branches

# deploy-non-prod:
#   stage: deploy
#   tags:
#     - $RUNNER
#   image: ruby:3.2-rc
#   script:
#     - apt-get update -qy
#     - apt-get install -y ruby-dev
#     - gem install dpl
#     - export PATH=$PATH:/usr/local/bundle/bin
#     - dpl --provider=heroku --app=$heroku_app_name_test --api-key=$heroku_api_key
#   environment:
#     name: staging
#     url: https://trip-mate-grp16-test.herokuapp.com/
#   only:
#     - develop

# # Ref: https://docs.gitlab.com/ee/ci/examples/deployment/index.html

# deploy-prod:
#   stage: deploy
#   tags:
#     - $RUNNER
#   image: ruby:3.2-rc
#   script:
#     - apt-get update -qy
#     - apt-get install -y ruby-dev
#     - gem install dpl
#     - export PATH=$PATH:/usr/local/bundle/bin
#     - dpl --provider=heroku --app=$heroku_app_name --api-key=$heroku_api_key
#   environment:
#     name: production
#     url: https://trip-mate-grp16.herokuapp.com/
#   only:
#     - main

# # Ref: https://dal.brightspace.com/d2l/le/content/230468/viewContent/3095849/View?ou=230468